name: Create dependencies

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  upload-to-artifactory:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: latest
      env:
        JF_URL: ${{ vars.JF_URL }}
        JF_USER: ${{ vars.JF_USER }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        
    - name: Download file from Artifactory
      run: jf rt download commons-dev-generic-local/build-tests/README.md README-new.md

    - name: Append new line to README-new.md
      run: |
        echo "* this is a new line" >> README-new.md

    - name: Upload README.md to Artifactory
      run: |
        jf rt upload README-new.md commons-dev-generic-local/build-tests-new/README.md


